version: 0.0
os: linux
files:
   - source: /App
     destination: /var/www/edge/htdocs
permissions:
   - object: /var/www/edge
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
    - location: scripts/stop_server.sh
      runas: root
   AfterInstall:
    - location: scripts/setup_edge.sh
      runas: root
    - location: scripts/start_server.sh
      runas: root