<?php
return [
	'button' => '<button class="btn btn-default {{class}}" {{attrs}}>{{text}}</button>',
//	'checkbox' => '<input type="checkbox" name="{{name}}" value="{{value}}"{{attrs}}>',
//	'checkboxFormGroup' => '{{label}}',
//	'checkboxWrapper' => '<div class="checkbox">{{label}}</div>',
//	'dateWidget' => '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}{{meridian}}',
//	'error' => '<div class="col-md-3 error-message">{{content}}</div>',
	'error' => '<span class="label label-danger">{{content}}</span>',
//	'errorList' => '<ul>{{content}}</ul>',
//	'errorItem' => '<li>{{text}}</li>',
//	'file' => '<input type="file" name="{{name}}"{{attrs}}>',
//	'fieldset' => '<fieldset{{attrs}}>{{content}}</fieldset>',
	'formStart' => '<form class="form-horizontal" {{attrs}}>',
//	'formEnd' => '</form>',
//	'formGroup' => '{{label}}{{input}}',
//	'hiddenBlock' => '<div style="display:none;">{{content}}</div>',
	'input' => '<div class="col-md-7 {{divclass}}"><input type="{{type}}" name="{{name}}" placeholder="{{placeholder}}" class="form-control" {{attrs}}/></div>',
	'inputSubmit' => '<button class="btn btn-success" type="{{type}}"{{attrs}}>Save</button>',
	'inputContainer' => '<div class="form-group {{type}}{{required}}">{{content}}</div>',
	'inputContainerError' => '<div class="form-group {{type}}{{required}}">{{content}}{{error}}</div>',
//	'inputContainerError' => '<div class="input {{type}}{{required}} error">{{content}}{{error}}</div>',
	'label' => '<label{{attrs}} class="col-md-2 control-label {{divclass}}">{{text}}</label>',
//	'nestingLabel' => '{{hidden}}<label{{attrs}}>{{input}}{{text}}</label>',
//	'legend' => '<legend>{{text}}</legend>',
//	'option' => '<option value="{{value}}"{{attrs}}>{{text}}</option>',
//	'optgroup' => '<optgroup label="{{label}}"{{attrs}}>{{content}}</optgroup>',
	'select' => '<div class="col-md-7 {{divclass}}"><select name="{{name}}" class="form-control" {{attrs}}>{{content}}</select></div>',
//	'selectMultiple' => '<select name="{{name}}[]" multiple="multiple"{{attrs}}>{{content}}</select>',
//	'radio' => '<input type="radio" name="{{name}}" value="{{value}}"{{attrs}}>',
//	'radioWrapper' => '{{label}}',
//	'textarea' => '<textarea name="{{name}}"{{attrs}}>{{value}}</textarea>',
	'submitContainer' => '<div class="form-group"><div class="col-md-offset-2 col-md-10">{{content}}</div></div>',
];
