USE edge;
DELETE FROM phinxlog where version > '20150824213600';


SELECT * FROM armour;
SELECT * FROM careers;
SELECT * FROM characters;
SELECT * FROM characters_armour;
SELECT * FROM characters_items;
SELECT * FROM characters_notes;
SELECT * FROM characters_skills;
SELECT * FROM characters_talents;
SELECT * FROM characters_weapons;
SELECT * FROM groups;
SELECT * FROM item_types;
SELECT * FROM items;
SELECT * FROM notes;
SELECT * FROM obligations;
SELECT * FROM phinxlog;
SELECT * FROM ranges;
SELECT * FROM skills ORDER BY name;
SELECT * FROM slack;
SELECT * FROM specialisations ORDER BY name;
SELECT * FROM species;
SELECT * FROM stats;
SELECT * FROM talents ORDER BY name;
SELECT * FROM users;
SELECT * FROM weapon_types;
SELECT * FROM weapons ORDER BY name;
SELECT * FROM xp ORDER BY modified DESC;

-- v0.3 to v0.4
ALTER TABLE obligations ADD note varchar(45) AFTER type;
UPDATE obligations SET created = NOW() WHERE created IS NULL;
UPDATE obligations SET modified = NOW() WHERE modified IS NULL;
UPDATE users SET created = NOW() WHERE created IS NULL;
UPDATE users SET modified = NOW() WHERE modified IS NULL;
UPDATE armour SET created = NOW() WHERE created IS NULL;
UPDATE armour SET modified = NOW() WHERE modified IS NULL;
UPDATE groups SET created = NOW() WHERE created IS NULL;
UPDATE groups SET modified = NOW() WHERE modified IS NULL;

DROP TABLE armour;
DROP TABLE careers;
DROP TABLE characters;
DROP TABLE characters_armour;
DROP TABLE characters_items;
DROP TABLE characters_notes;
DROP TABLE characters_skills;
DROP TABLE characters_talents;
DROP TABLE characters_weapons;
DROP TABLE groups;
DROP TABLE item_types;
DROP TABLE items;
DROP TABLE notes;
DROP TABLE obligations;
DROP TABLE phinxlog;
DROP TABLE ranges;
DROP TABLE skills;
DROP TABLE slack;
DROP TABLE specialisations;
DROP TABLE species;
DROP TABLE stats;
DROP TABLE talents;
DROP TABLE users;
DROP TABLE weapon_types;
DROP TABLE weapons;
DROP TABLE xp;
